[package]
name = "assay-ebpf"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
aya-ebpf = { git = "https://github.com/aya-rs/aya", tag = "v0.13.0" }
aya-log-ebpf = { git = "https://github.com/aya-rs/aya", tag = "v0.13.0" }
assay-common = { path = "../assay-common" }

[[bin]]
name = "assay-ebpf"
path = "src/main.rs"

[profile.dev]
panic = "abort"
lto = true

[profile.release]
panic = "abort"
lto = true
