[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "python-sdk-demo"
version = "0.1.0"
dependencies = [
    "pytest",
    "assay",
]

[tool.hatch.metadata]
allow-direct-references = true
