[package]
name = "assay-common"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = ["serde/std", "chrono/std", "serde_json/std"]

[dependencies]
serde = { version = "1.0", features = ["derive"], default-features = false }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
chrono = { version = "0.4", features = ["serde"], default-features = false, optional = true }
