[package]
name = "assay-monitor"
version = "1.8.0"
edition = "2021"

[dependencies]
assay-common = { path = "../assay-common" }
thiserror = "1"
anyhow = "1"
tokio = { version = "1", features = ["sync"] }
tokio-stream = "0.1"

# Linux-only eBPF stack
[target.'cfg(target_os = "linux")'.dependencies]
aya = "0.12"


